### ISSUE TITLE
`<=` raises Syntax error

### ISSUE THREAD

**Issue by jinulee-v** [SWI-Prolog/sCASP#4]
Thank you for this wonderful repo.
There seems to be a bug regarding inequality `<=`. While all other inequalities are accepted, only _less than or equal_ raises error...
![image](https://github.com/SWI-Prolog/sCASP/assets/76199370/0200e7a3-fc3b-4d43-9456-bb3d97c570e9)

**Comment by eshelyaron** [comment]
Hi there, in Prolog (and in s(CASP)), less than or equal to is written `=<`, not `<=`.  Does that work?

**Comment by jinulee-v** [comment]
Wow, I was not aware about it!
Clingo supports <= instead of =<, and that was confusing...
