### ISSUE TITLE
'Strict' negation as failure algorithm (forall)

### ISSUE THREAD

**Issue by jinulee-v** [SWI-Prolog/sCASP#5]
I am currently having trouble working with negation as failure (`not a`).
My requirement is to treat negation as failure as a 'strict' constraint, so that if any fact meets the negated condition the proof fails.
i.e.,
```
c :- not b(X).
b(a).

?- c.
```
This program generates a proof `c <- not b(A | {A∉[a]})`, which is clearly explained in the s(CASP) paper. However, I wish this query to be failed(no valid proof), because there exists a fact `b(a)` . (i.e. closed-world semantics)
(fyi, I used clingo before moving on to s(CASP), which exactly demonstrates this behavior.)

As for my application, I may manually search for the character `∉` and declare failure; but I wonder if there is a general support for such execution option.
I have tried four different options via the command line argument `--forall`, but had no success.
Can I get any hints around this issue?

**Comment by jinulee-lbox** [comment]
I have solved the issue by modifying the `disequality.pl`.
The modification is needed within the `not_unify2/2` , as follows:
```
% - Constructive disunification of a negatively constrained variable
% and a non- variable value will always succeed, adding the
% "ground" value to the variable’s prohibited value list.
% EDIT: this should always fail.
not_unify2(A, B) :-
    ground(B),
    neg_var(A, NegListA), % NegListA is unused(singleton), but no effect
    !, fail. % Add this line
    % Remove the following lines:
    % ord_add_element(NegListA, B, NegList),
    % update(A, NegList).
```

**Comment by jinulee-v** [comment]
I have solved the issue by modifying the `disequality.pl`.
The modification is needed within the `not_unify2/2` , as follows:
```
% - Constructive disunification of a negatively constrained variable
% and a non- variable value will always succeed, adding the
% "ground" value to the variable’s prohibited value list.
% EDIT: this should always fail.
not_unify2(A, B) :-
    ground(B),
    neg_var(A, NegListA), % NegListA is unused(singleton), but no effect
    !, fail. % Add this line
    % Remove the following lines:
    % ord_add_element(NegListA, B, NegList),
    % update(A, NegList).
```

**Comment by jinulee-lbox** [comment]
Small additional modification is needed to ensure correct proof tree for NMR constraints:
`stack.pl` line 153-154 should be modified as
```prolog
selected(-(Goal), _) =>
    \+ aux_predicate(Goal).
```

**Comment by jinulee-v** [comment]
After a desperate struggle, I finally concluded to leave s(CASP) as it is.

Several implications that I have found out:
1. `forall` is mandatory to implement the correct proof of 'negation as failure'.
2. (until now) I have no idea how to constrain forall in the closed world domain.

**Comment by jinulee-v** [comment]
My final conclusion is that for implementing conventional Negation As Failure(NAF) semantics, `body_vars/3` should be modified.

In this simple example,
```prolog
a :- not b(X), c(Y).
% Dual:   not a :- forall(X, forall(Y, not a2(X, Y))).
%            not a2(X, Y) :- b(X).
%            not a2(X, Y) :- b(X), not c(Y).
b(x).
?- not a.
```
, s(CASP) fails find a proof due to a `forall` wrapped for variable `X`. Even though not a2(X, Y) holds for X=x, the forall construct leads to a search for `X | X ∉ [x]` which eventually fails.
Therefore, we need to exclude the negatively scoped variables when wrapping with `forall` statement. Correct dual (under NAF sematics) will be:
```prolog
a :- not b(X), c(Y).
% Dual:   not a :-  forall(Y, not a2(X, Y)).  % No forall for X!
%            not a2(X, Y) :- b(X).
%            not a2(X, Y) :- b(X), not c(Y).
b(x).
?- not a.
```
Dual of this requirement also holds, that if the rule head is negated we should discard variables that only appear in the positive scope. Demonstration:
```
not d :- not b(X), c(Y).
% Dual:   d :-  forall(X, d2(X, Y)).  % No forall for Y!
%            d2(X, Y) :- b(X).
%            d2(X, Y) :- b(X), not c(Y).
```

Few changes in `variables.py` can achieve this manner.
1. Split `body_vars/3` into two cases, where head is a normal literal or negated.
2. Implement multiple version of `term_vars`, to exclude negated/positive body literals. Since current implementation do not discriminate between list and functions, we should also split these cases.
